/**
 * Represents a single message in the conversation
 * @interface Message
 */
export interface Message {
    /** Unique identifier for the message */
    id: string;
    /** Role of the message sender - either user or AI */
    role: 'user' | 'ai';
    /** The actual content/text of the message */
    content: string;
    /** Unix timestamp of when the message was created */
    timestamp: number;
    /** Optional identifier for the question this message might be an answer to */
    questionId?: string;
}

/**
 * Represents the dynamically collected concept data during the conversation,
 * where keys are category names and values are the collected text.
 * @interface ConceptData
 */
export interface ConceptData {
    [key: string]: string;
}

/**
 * Represents the structured data for a video concept after processing or for specific models.
 * @interface StructuredConceptData
 */
export interface StructuredConceptData {
    /** Detailed description of the video concept */
    conceptDetails: string;
    /** Array of key messages or points to be conveyed in the video */
    keyMessages: string[];
    /** Description of the visual style and aesthetic for the video */
    visualStyle: string;
}

/**
 * Represents a complete conversation session
 * @interface Conversation
 */
export interface Conversation {
    /** Array of all messages exchanged during the conversation */
    messages: Message[];
    /** Structured data collected about the video concept. Uses the structured form. */
    conceptData: StructuredConceptData;
}

/**
 * Represents a processed conversation with additional analysis and metadata
 * @interface ProcessedConversation
 */
export interface ProcessedConversation {
    /** Unix timestamp when the conversation was completed */
    completedAt: number;
    /** Structured (or processed) data about the video concept. Uses the structured form. */
    conceptData: StructuredConceptData;
    /** Array of key messages extracted from the conversation */
    keyMessages: string[];
    /** Final visual style description */
    visualStyle: string;
    /** Array of all messages exchanged during the conversation */
    messages: Message[];
    /** Unique identifier for the conversation session */
    sessionId: string;
    /** Confidence scores for different aspects of the concept */
    confidenceScores: {
        /** How clear the target audience is defined */
        audienceClarity: number;
        /** How well-defined the concept is */
        conceptClarity: number;
        /** How specific the visual style description is */
        styleSpecificity: number;
    };
    /** Array of semantic tags extracted from the conversation */
    semanticTags: string[];
}

/**
 * Defines the structure for the video concept summary generated by the AI.
 * @interface VideoConceptSummary
 */
export interface VideoConceptSummary {
    videoTitleSuggestion: string;
    coreConcept: string;
    targetAudience: {
        description: string;
        keyTakeaways: string[];
    };
    keyMessages: string[];
    visualElements: {
        style: string;
        moodTone: string;
        imagerySuggestions: string[];
        colorPalette: string;
    };
    contentStructureOutline: Array<{
        section: string;
        description: string;
    }>;
    additionalNotes: string;
    technicalSpecifications?: { // Optional, or provide default values
        resolution?: string;
        aspectRatio?: string;
        targetDuration?: string;  // required
    };
    savedAt?: any;
    lastUpdatedAt?: any; // Firestore Timestamp or string/number representation
}